// DownloadReports.js
import jsPDF from "jspdf";

const DownloadReports = ({ user, prediction, uploadedImageUrl }) => {
  const downloadReport = () => {
    const doc = new jsPDF();

    // Header
    doc.setFillColor(41, 128, 185); // Blue header
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.text("MRI Tumor Detection Report", 105, 20, { align: "center" });

    // Reset color
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);

    // Patient Info Section
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text("Patient Information", 20, 45);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 47, 190, 47);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.text(`Name:`, 20, 60);
    doc.text(`${user.first_name} ${user.last_name}`, 60, 60);

    doc.text(`Email:`, 20, 70);
    doc.text(`${user.email}`, 60, 70);

    doc.text(`Phone:`, 20, 80);
    doc.text(`${user.phone}`, 60, 80);

    doc.text(`Gender:`, 20, 90);
    doc.text(`${user.gender}`, 60, 90);

    doc.text(`DOB:`, 20, 100);
    doc.text(`${user.date_of_birth}`, 60, 100);

    // Prediction Section
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text("Prediction Results", 20, 120);
    doc.line(20, 122, 190, 122);

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Prediction:`, 20, 135);
    doc.setTextColor(231, 76, 60); // Red for emphasis
    doc.text(`${prediction.data.prediction}`, 60, 135);

    doc.setTextColor(0, 0, 0);
    doc.text(`Confidence:`, 20, 145);
    doc.setTextColor(39, 174, 96); // Green for confidence
    doc.text(`${prediction.data.confidence.toFixed(2)}%`, 60, 145);

    // Model Info Section
    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text("Model Information", 20, 165);
    doc.line(20, 167, 190, 167);

    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Model: VGG16 Transfer Learning`, 20, 180);
    doc.text(`Accuracy: 97.22%`, 20, 190);
    doc.text(`Class Labels: pituitary, glioma, meningioma, notumor`, 20, 200);

    // MRI Image Section
    if (uploadedImageUrl) {
      doc.setFontSize(14);
      doc.setTextColor(41, 128, 185);
      doc.text("Uploaded MRI Image", 20, 220);
      doc.line(20, 222, 190, 222);

      doc.addImage(uploadedImageUrl, "JPEG", 20, 230, 70, 50);
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by MRI Tumor Detection System © 2025", 105, 290, {
      align: "center",
    });

    // Save PDF
    doc.save("MRI_Tumor_Report.pdf");
  };

  return (
    <button className="btn btn-outline-primary" onClick={downloadReport}>
      <i className="fas fa-download me-2"></i>
      Download Report
    </button>
  );
};

export default DownloadReports;
